os: windows

language: cpp

env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"

install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe msvc/barelymusician_test/barelymusician_test.vcxproj -t:restore
  - MSBuild.exe -p:SolutionDir="../" -p:Configuration=Debug -p:Platform=x64 msvc/barelymusician_test/barelymusician_test.vcxproj
  - msvc/x64/Debug/barelymusician_test.exe
