/**
 * Command types to process.
 * @enum {int}
 */
export const CommandType = Object.freeze({
  ENGINE_SET_TEMPO: 0,
  ENGINE_SET_CONTROL: 1,

  INSTRUMENT_CREATE: 2,
  INSTRUMENT_DESTROY: 3,
  INSTRUMENT_ON_NOTE_ON: 4,
  INSTRUMENT_ON_NOTE_OFF: 5,
  INSTRUMENT_SET_ALL_NOTES_OFF: 6,
  INSTRUMENT_SET_CONTROL: 7,
  INSTRUMENT_SET_NOTE_CONTROL: 8,
  INSTRUMENT_SET_NOTE_ON: 9,
  INSTRUMENT_SET_NOTE_OFF: 10,
  INSTRUMENT_SET_SAMPLE_DATA: 11,

  PERFORMER_CREATE: 12,
  PERFORMER_DESTROY: 13,
  PERFORMER_SET_LOOPING: 14,
  PERFORMER_SET_LOOP_BEGIN_POSITION: 15,
  PERFORMER_SET_LOOP_LENGTH: 16,
  PERFORMER_SET_POSITION: 17,
  PERFORMER_START: 18,
  PERFORMER_STOP: 19,
  PERFORMER_SYNC_TO: 20,

  TASK_CREATE: 21,
  TASK_DESTROY: 22,
  TASK_ON_EVENT: 23,
  TASK_SET_DURATION: 24,
  TASK_SET_POSITION: 25,
  TASK_SET_PRIORITY: 26,
});

/**
 * Message types to communicate with `barelymusician-processor`.
 * @enum {int}
 */
export const MessageType = Object.freeze({
  INIT_SUCCESS: 0,
  UPDATE: 1,
  UPDATE_SUCCESS: 2,
});
