export const EngineControlType = Object.freeze({
  COMP_MIX: 0,
  COMP_ATTACK: 1,
  COMP_RELEASE: 2,
  COMP_THRESHOLD: 3,
  COMP_RATIO: 4,
  DELAY_MIX: 5,
  DELAY_TIME: 6,
  DELAY_FEEDBACK: 7,
  DELAY_LPF_CUTOFF: 8,
  DELAY_HPF_CUTOFF: 9,
  DELAY_PING_PONG: 10,
  DELAY_REVERB_SEND: 11,
  REVERB_MIX: 12,
  REVERB_DAMPING: 13,
  REVERB_ROOM_SIZE: 14,
  REVERB_STEREO_WIDTH: 15,
  REVERB_FREEZE: 16,
  SIDECHAIN_MIX: 17,
  SIDECHAIN_ATTACK: 18,
  SIDECHAIN_RELEASE: 19,
  SIDECHAIN_THRESHOLD: 20,
  SIDECHAIN_RATIO: 21,
  COUNT: 22,
});

export const InstrumentControlType = Object.freeze({
  GAIN: 0,
  PITCH_SHIFT: 1,
  STEREO_PAN: 2,
  ATTACK: 3,
  DECAY: 4,
  SUSTAIN: 5,
  RELEASE: 6,
  SLICE_MODE: 7,
  OSC_MIX: 8,
  OSC_MODE: 9,
  OSC_NOISE_MIX: 10,
  OSC_PITCH_SHIFT: 11,
  OSC_SHAPE: 12,
  OSC_SKEW: 13,
  CRUSH_DEPTH: 14,
  CRUSH_RATE: 15,
  DISTORTION_MIX: 16,
  DISTORTION_DRIVE: 17,
  FILTER_CUTOFF: 18,
  FILTER_RESONANCE: 19,
  DELAY_SEND: 20,
  REVERB_SEND: 21,
  SIDECHAIN_SEND: 22,
  ARP_MODE: 23,
  ARP_GATE: 24,
  ARP_RATE: 25,
  RETRIGGER: 26,
  VOICE_COUNT: 27,
  COUNT: 28,
});

export const NoteControlType = Object.freeze({
  GAIN: 0,
  PITCH_SHIFT: 1,
  COUNT: 2,
});

export const ArpMode = Object.freeze({
  NONE: 0,
  UP: 1,
  DOWN: 2,
  RANDOM: 3,
  COUNT: 4,
});

export const OscMode = Object.freeze({
  CROSSFADE: 0,
  AM: 1,
  FM: 2,
  MA: 3,
  MF: 4,
  RING: 5,
  COUNT: 6,
});

export const SliceMode = Object.freeze({
  SUSTAIN: 0,
  LOOP: 1,
  ONCE: 2,
  COUNT: 3,
});

export const ENGINE_CONTROLS = Object.freeze({
  [EngineControlType.COMP_MIX]: {
    name: 'Comp Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.COMP_ATTACK]: {
    name: 'Comp Attack',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 8.0,
  },
  [EngineControlType.COMP_RELEASE]: {
    name: 'Comp Release',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 8.0,
  },
  [EngineControlType.COMP_THRESHOLD]: {
    name: 'Comp Threshold',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.COMP_RATIO]: {
    name: 'Comp Ratio',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_MIX]: {
    name: 'Delay Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_TIME]: {
    name: 'Delay Time',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 8.0,
  },
  [EngineControlType.DELAY_FEEDBACK]: {
    name: 'Delay Feedback',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_LPF_CUTOFF]: {
    name: 'Delay Lpf Cutoff',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_HPF_CUTOFF]: {
    name: 'Delay Hpf Cutoff',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_PING_PONG]: {
    name: 'Delay Ping-Pong',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_REVERB_SEND]: {
    name: 'Delay Reverb Send',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 2.0,
  },
  [EngineControlType.REVERB_MIX]: {
    name: 'Reverb Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_DAMPING]: {
    name: 'Reverb Damping',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_ROOM_SIZE]: {
    name: 'Reverb Room Size',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_STEREO_WIDTH]: {
    name: 'Reverb Stereo Width',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_FREEZE]: {
    name: 'Reverb Freeze',
    valueType: 'bool',
    defaultValue: false,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_MIX]: {
    name: 'Sidechain Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_ATTACK]: {
    name: 'Sidechain Attack',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 8.0,
  },
  [EngineControlType.SIDECHAIN_RELEASE]: {
    name: 'Sidechain Release',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 8.0,
  },
  [EngineControlType.SIDECHAIN_THRESHOLD]: {
    name: 'Sidechain Threshold',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_RATIO]: {
    name: 'Sidechain Ratio',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
});

export const INSTRUMENT_CONTROLS = Object.freeze({
  [InstrumentControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
  [InstrumentControlType.STEREO_PAN]: {
    name: 'Stereo Pan',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ATTACK]: {
    name: 'Attack (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.DECAY]: {
    name: 'Decay (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.SUSTAIN]: {
    name: 'Sustain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.RELEASE]: {
    name: 'Release (sec)',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.SLICE_MODE]: {
    name: 'Slice Mode',
    valueType: SliceMode,
    defaultValue: SliceMode.SUSTAIN,
    minValue: 0,
    maxValue: SliceMode.COUNT - 1,
  },
  [InstrumentControlType.OSC_MIX]: {
    name: 'Osc Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_MODE]: {
    name: 'Osc Mode',
    valueType: OscMode,
    defaultValue: OscMode.CROSSFADE,
    minValue: 0,
    maxValue: OscMode.COUNT - 1,
  },
  [InstrumentControlType.OSC_NOISE_MIX]: {
    name: 'Osc Noise Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_PITCH_SHIFT]: {
    name: 'Osc Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -4.0,
    maxValue: 4.0,
  },
  [InstrumentControlType.OSC_SHAPE]: {
    name: 'Osc Shape',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_SKEW]: {
    name: 'Osc Skew',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.CRUSH_DEPTH]: {
    name: 'Crush Depth',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.CRUSH_RATE]: {
    name: 'Crush Rate',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_MIX]: {
    name: 'Distortion Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_DRIVE]: {
    name: 'Distortion Drive',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.FILTER_CUTOFF]: {
    name: 'Filter Cutoff',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.FILTER_RESONANCE]: {
    name: 'Filter Resonance',
    valueType: 'float',
    defaultValue: 0.5,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DELAY_SEND]: {
    name: 'Delay Send',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.REVERB_SEND]: {
    name: 'Reverb Send',
    valueType: 'float',
    defaultValue: 0.25,
    minValue: 0.0,
    maxValue: 2.0,
  },
  [InstrumentControlType.SIDECHAIN_SEND]: {
    name: 'Sidechain Send',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ARP_MODE]: {
    name: 'Arp Mode',
    valueType: ArpMode,
    defaultValue: ArpMode.NONE,
    minValue: 0,
    maxValue: ArpMode.COUNT - 1,
  },
  [InstrumentControlType.ARP_GATE]: {
    name: 'Arp Gate',
    valueType: 'float',
    defaultValue: 0.5,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ARP_RATE]: {
    name: 'Arp Rate',
    valueType: 'int',
    defaultValue: 2,
    minValue: 1,
    maxValue: 16,
  },
  [InstrumentControlType.RETRIGGER]: {
    name: 'Retrigger',
    valueType: 'bool',
    defaultValue: false,
    minValue: 0,
    maxValue: 1,
  },
  [InstrumentControlType.VOICE_COUNT]: {
    name: 'Voice Count',
    valueType: 'int',
    defaultValue: 8,
    minValue: 1,
    maxValue: 20,
  },
});

export const NOTE_CONTROLS = Object.freeze({
  [NoteControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [NoteControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
});
