export const EngineControlType = Object.freeze({
  COMPRESSOR_MIX: 0,
  COMPRESSOR_ATTACK: 1,
  COMPRESSOR_RELEASE: 2,
  COMPRESSOR_THRESHOLD: 3,
  COMPRESSOR_RATIO: 4,
  DELAY_MIX: 5,
  DELAY_TIME: 6,
  DELAY_FEEDBACK: 7,
  DELAY_LOW_PASS_CUTOFF: 8,
  DELAY_HIGH_PASS_CUTOFF: 9,
  DELAY_REVERB_SEND: 10,
  REVERB_MIX: 11,
  REVERB_DAMPING_RATIO: 12,
  REVERB_ROOM_SIZE: 13,
  REVERB_STEREO_WIDTH: 14,
  REVERB_FREEZE: 15,
  SIDECHAIN_MIX: 16,
  SIDECHAIN_ATTACK: 17,
  SIDECHAIN_RELEASE: 18,
  SIDECHAIN_THRESHOLD: 19,
  SIDECHAIN_RATIO: 20,
  COUNT: 21,
});

export const InstrumentControlType = Object.freeze({
  GAIN: 0,
  PITCH_SHIFT: 1,
  RETRIGGER: 2,
  STEREO_PAN: 3,
  VOICE_COUNT: 4,
  ATTACK: 5,
  DECAY: 6,
  SUSTAIN: 7,
  RELEASE: 8,
  OSC_MIX: 9,
  OSC_MODE: 10,
  OSC_NOISE_MIX: 11,
  OSC_PITCH_SHIFT: 12,
  OSC_SHAPE: 13,
  OSC_SKEW: 14,
  SLICE_MODE: 15,
  BIT_CRUSHER_DEPTH: 16,
  BIT_CRUSHER_RATE: 17,
  DISTORTION_MIX: 18,
  DISTORTION_DRIVE: 19,
  FILTER_TYPE: 20,
  FILTER_CUTOFF: 21,
  FILTER_Q: 22,
  DELAY_SEND: 23,
  REVERB_SEND: 24,
  SIDECHAIN_SEND: 25,
  ARP_MODE: 26,
  ARP_GATE_RATIO: 27,
  ARP_RATE: 28,
  COUNT: 29,
});

export const NoteControlType = Object.freeze({
  GAIN: 0,
  PITCH_SHIFT: 1,
  COUNT: 2,
});

export const ArpMode = Object.freeze({
  NONE: 0,
  UP: 1,
  DOWN: 2,
  RANDOM: 3,
  COUNT: 4,
});

export const FilterType = Object.freeze({
  NONE: 0,
  LOW_PASS: 1,
  HIGH_PASS: 2,
  COUNT: 3,
});

export const OscMode = Object.freeze({
  MIX: 0,
  AM: 1,
  ENVELOPE_FOLLOWER: 2,
  FM: 3,
  MF: 4,
  RING: 5,
  COUNT: 6,
});

export const SliceMode = Object.freeze({
  SUSTAIN: 0,
  LOOP: 1,
  ONCE: 2,
  COUNT: 3,
});

export const ENGINE_CONTROLS = Object.freeze({
  [EngineControlType.COMPRESSOR_MIX]: {
    name: 'Compressor Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.COMPRESSOR_ATTACK]: {
    name: 'Compressor Attack',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [EngineControlType.COMPRESSOR_RELEASE]: {
    name: 'Compressor Release',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [EngineControlType.COMPRESSOR_THRESHOLD]: {
    name: 'Compressor Threshold',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.COMPRESSOR_RATIO]: {
    name: 'Compressor Ratio',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 1.0,
    maxValue: 64.0,
  },
  [EngineControlType.DELAY_MIX]: {
    name: 'Delay Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_TIME]: {
    name: 'Delay Time',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [EngineControlType.DELAY_FEEDBACK]: {
    name: 'Delay Feedback',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_LOW_PASS_CUTOFF]: {
    name: 'Delay Low-Pass Cutoff',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_HIGH_PASS_CUTOFF]: {
    name: 'Delay High-Pass Cutoff',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.DELAY_REVERB_SEND]: {
    name: 'Delay Reverb Send',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 2.0,
  },
  [EngineControlType.REVERB_MIX]: {
    name: 'Reverb Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_DAMPING_RATIO]: {
    name: 'Reverb Damping Ratio',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_ROOM_SIZE]: {
    name: 'Reverb Room Size',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_STEREO_WIDTH]: {
    name: 'Reverb Stereo Width',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.REVERB_FREEZE]: {
    name: 'Reverb Freeze',
    valueType: 'bool',
    defaultValue: false,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_MIX]: {
    name: 'Sidechain Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_ATTACK]: {
    name: 'Sidechain Attack',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [EngineControlType.SIDECHAIN_RELEASE]: {
    name: 'Sidechain Release',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [EngineControlType.SIDECHAIN_THRESHOLD]: {
    name: 'Sidechain Threshold',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [EngineControlType.SIDECHAIN_RATIO]: {
    name: 'Sidechain Ratio',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 1.0,
    maxValue: 64.0,
  },
});

export const INSTRUMENT_CONTROLS = Object.freeze({
  [InstrumentControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
  [InstrumentControlType.RETRIGGER]: {
    name: 'Retrigger',
    valueType: 'bool',
    defaultValue: false,
    minValue: 0,
    maxValue: 1,
  },
  [InstrumentControlType.STEREO_PAN]: {
    name: 'Stereo Pan',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.VOICE_COUNT]: {
    name: 'Voice Count',
    valueType: 'int',
    defaultValue: 8,
    minValue: 1,
    maxValue: 20,
  },
  [InstrumentControlType.ATTACK]: {
    name: 'Attack (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.DECAY]: {
    name: 'Decay (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.SUSTAIN]: {
    name: 'Sustain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.RELEASE]: {
    name: 'Release (sec)',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.OSC_MIX]: {
    name: 'Osc Mix',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_MODE]: {
    name: 'Osc Mode',
    valueType: OscMode,
    defaultValue: OscMode.MIX,
    minValue: 0,
    maxValue: OscMode.COUNT - 1,
  },
  [InstrumentControlType.OSC_NOISE_MIX]: {
    name: 'Osc Noise Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_PITCH_SHIFT]: {
    name: 'Osc Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -4.0,
    maxValue: 4.0,
  },
  [InstrumentControlType.OSC_SHAPE]: {
    name: 'Osc Shape',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_SKEW]: {
    name: 'Osc Skew',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -0.25,
    maxValue: 0.25,
  },
  [InstrumentControlType.SLICE_MODE]: {
    name: 'Slice Mode',
    valueType: SliceMode,
    defaultValue: SliceMode.SUSTAIN,
    minValue: 0,
    maxValue: SliceMode.COUNT - 1,
  },
  [InstrumentControlType.BIT_CRUSHER_DEPTH]: {
    name: 'Bitcrusher Depth',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.BIT_CRUSHER_RATE]: {
    name: 'Bitcrusher Rate',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_MIX]: {
    name: 'Distortion Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_DRIVE]: {
    name: 'Distortion Drive',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.FILTER_TYPE]: {
    name: 'Filter Type',
    valueType: FilterType,
    defaultValue: FilterType.NONE,
    minValue: 0,
    maxValue: FilterType.COUNT - 1,
  },
  [InstrumentControlType.FILTER_CUTOFF]: {
    name: 'Filter Cutoff',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.FILTER_Q]: {
    name: 'Filter Q',
    valueType: 'float',
    defaultValue: Math.sqrt(0.5),
    minValue: 0.1,
    maxValue: 10,
  },
  [InstrumentControlType.DELAY_SEND]: {
    name: 'Delay Send',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.REVERB_SEND]: {
    name: 'Reverb Send',
    valueType: 'float',
    defaultValue: 0.25,
    minValue: 0.0,
    maxValue: 2.0,
  },
  [InstrumentControlType.SIDECHAIN_SEND]: {
    name: 'Sidechain Send',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ARP_MODE]: {
    name: 'Arp Mode',
    valueType: ArpMode,
    defaultValue: ArpMode.NONE,
    minValue: 0,
    maxValue: ArpMode.COUNT - 1,
  },
  [InstrumentControlType.ARP_GATE_RATIO]: {
    name: 'Arp Gate Ratio',
    valueType: 'float',
    defaultValue: 0.5,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ARP_RATE]: {
    name: 'Arp Rate',
    valueType: 'int',
    defaultValue: 2,
    minValue: 1,
    maxValue: 16,
  },
});

export const NOTE_CONTROLS = Object.freeze({
  [NoteControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [NoteControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
});
