export const ArpMode = {
  NONE: 0,
  UP: 1,
  DOWN: 2,
  RANDOM: 3,
  COUNT: 4,
};

export const InstrumentControlType = {
  GAIN: 0,
  PITCH_SHIFT: 1,
  RETRIGGER: 2,
  STEREO_PAN: 3,
  VOICE_COUNT: 4,
  ATTACK: 5,
  DECAY: 6,
  SUSTAIN: 7,
  RELEASE: 8,
  OSC_MIX: 9,
  OSC_MODE: 10,
  OSC_NOISE_MIX: 11,
  OSC_PITCH_SHIFT: 12,
  OSC_SHAPE: 13,
  OSC_SKEW: 14,
  SLICE_MODE: 15,
  BIT_CRUSHER_DEPTH: 16,
  BIT_CRUSHER_RATE: 17,
  DISTORTION_AMOUNT: 18,
  DISTORTION_DRIVE: 19,
  FILTER_TYPE: 20,
  FILTER_FREQUENCY: 21,
  FILTER_Q: 22,
  DELAY_SEND: 23,
  SIDECHAIN_SEND: 24,
  ARP_MODE: 25,
  ARP_GATE_RATIO: 26,
  ARP_RATE: 27,
  COUNT: 28,
};

export const FilterType = {
  NONE: 0,
  LOW_PASS: 1,
  HIGH_PASS: 2,
  COUNT: 3,
};

export const NoteControlType = {
  GAIN: 0,
  PITCH_SHIFT: 1,
  COUNT: 2,
};

export const OscMode = {
  MIX: 0,
  AM: 1,
  ENVELOPE_FOLLOWER: 2,
  FM: 3,
  MF: 4,
  RING: 5,
  COUNT: 6,
};

export const SliceMode = {
  SUSTAIN: 0,
  LOOP: 1,
  ONCE: 2,
  COUNT: 3,
};

export const CONTROLS = {
  [InstrumentControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 0.25,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
  // [InstrumentControlType.RETRIGGER]: {
  //   name: 'Retrigger',
  //   valueType: 'bool',
  //   defaultValue: false,
  //   minValue: 0,
  //   maxValue: 1,
  // },
  [InstrumentControlType.STEREO_PAN]: {
    name: 'Stereo Pan',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -1.0,
    maxValue: 1.0,
  },
  // [InstrumentControlType.VOICE_COUNT]: {
  //   name: 'Voice Count',
  //   valueType: 'int',
  //   defaultValue: 8,
  //   minValue: 1,
  //   maxValue: 20,
  // },
  [InstrumentControlType.ATTACK]: {
    name: 'Attack (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.DECAY]: {
    name: 'Decay (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 5.0,
  },
  [InstrumentControlType.SUSTAIN]: {
    name: 'Sustain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.RELEASE]: {
    name: 'Release (sec)',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 5.0,
  },
  // [InstrumentControlType.OSC_MIX]: {
  //   name: 'Osc Mix',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: 0.0,
  //   maxValue: 1.0,
  // },
  // [InstrumentControlType.OSC_MODE]: {
  //   name: 'Osc Mode',
  //   valueType: 'int',
  //   defaultValue: OscMode.MIX,
  //   minValue: 0,
  //   maxValue: OscMode.COUNT - 1,
  // },
  [InstrumentControlType.OSC_NOISE_MIX]: {
    name: 'Osc Noise Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  // [InstrumentControlType.OSC_PITCH_SHIFT]: {
  //   name: 'Osc Pitch Shift',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: -4.0,
  //   maxValue: 4.0,
  // },
  [InstrumentControlType.OSC_SHAPE]: {
    name: 'Osc Shape',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.OSC_SKEW]: {
    name: 'Osc Skew',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -0.25,
    maxValue: 0.25,
  },
  // [InstrumentControlType.SLICE_MODE]: {
  //   name: 'Slice Mode',
  //   valueType: 'int',
  //   defaultValue: SliceMode.SUSTAIN,
  //   minValue: 0,
  //   maxValue: SliceMode.COUNT - 1,
  // },
  [InstrumentControlType.BIT_CRUSHER_DEPTH]: {
    name: 'Bitcrusher Depth',
    valueType: 'float',
    defaultValue: 16.0,
    minValue: 1.0,
    maxValue: 16.0,
  },
  [InstrumentControlType.BIT_CRUSHER_RATE]: {
    name: 'Bitcrusher Rate',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_AMOUNT]: {
    name: 'Distortion Amount',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.DISTORTION_DRIVE]: {
    name: 'Distortion Drive',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 20.0,
  },
  // [InstrumentControlType.FILTER_TYPE]: {
  //   name: 'Filter Type',
  //   valueType: 'int',
  //   defaultValue: FilterType.NONE,
  //   minValue: 0,
  //   maxValue: FilterType.COUNT - 1,
  // },
  // [InstrumentControlType.FILTER_FREQUENCY]: {
  //   name: 'Filter Frequency',
  //   valueType: 'float',
  //   defaultValue: 48000.0,
  //   minValue: 0.0,
  //   maxValue: 48000.0,
  // },
  // [InstrumentControlType.FILTER_Q]: {
  //   name: 'Filter Q',
  //   valueType: 'float',
  //   defaultValue: Math.sqrt(0.5),
  //   minValue: 0.1,
  //   maxValue: 10,
  // },
  [InstrumentControlType.DELAY_SEND]: {
    name: 'Delay Send',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 1.0,
  },
  // [InstrumentControlType.SIDECHAIN_SEND]: {
  //   name: 'Sidechain Send',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: -1.0,
  //   maxValue: 1.0,
  // },
  [InstrumentControlType.ARP_MODE]: {
    name: 'Arp Mode',
    valueType: 'int',
    defaultValue: ArpMode.NONE,
    minValue: 0,
    maxValue: ArpMode.COUNT - 1,
  },
  [InstrumentControlType.ARP_GATE_RATIO]: {
    name: 'Arp Gate Ratio',
    valueType: 'float',
    defaultValue: 0.5,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [InstrumentControlType.ARP_RATE]: {
    name: 'Arp Rate',
    valueType: 'int',
    defaultValue: 2,
    minValue: 1,
    maxValue: 16,
  },
};
