export const ControlType = {
  GAIN: 0,
  PITCH_SHIFT: 1,
  RETRIGGER: 2,
  STEREO_PAN: 3,
  VOICE_COUNT: 4,
  ATTACK: 5,
  DECAY: 6,
  SUSTAIN: 7,
  RELEASE: 8,
  OSC_MIX: 9,
  OSC_MODE: 10,
  OSC_NOISE_MIX: 11,
  OSC_PITCH_SHIFT: 12,
  OSC_SHAPE: 13,
  OSC_SKEW: 14,
  SLICE_MODE: 15,
  FILTER_TYPE: 16,
  FILTER_FREQUENCY: 17,
  FILTER_Q: 18,
  BIT_CRUSHER_DEPTH: 19,
  BIT_CRUSHER_RATE: 20,
  COUNT: 21,
};

export const FilterType = {
  NONE: 0,
  LOW_PASS: 1,
  HIGH_PASS: 2,
  COUNT: 3,
};

export const NoteControlType = {
  GAIN: 0,
  PITCH_SHIFT: 1,
  COUNT: 2,
};

export const OscMode = {
  MIX: 0,
  AM: 1,
  ENVELOPE_FOLLOWER: 2,
  FM: 3,
  MF: 4,
  RING: 5,
  COUNT: 6,
};

export const SliceMode = {
  SUSTAIN: 0,
  LOOP: 1,
  ONCE: 2,
  COUNT: 3,
};

export const CONTROLS = {
  [ControlType.GAIN]: {
    name: 'Gain',
    valueType: 'float',
    defaultValue: 0.25,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [ControlType.PITCH_SHIFT]: {
    name: 'Pitch Shift',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -2.0,
    maxValue: 2.0,
  },
  // [ControlType.RETRIGGER]: {
  //   name: 'Retrigger',
  //   valueType: 'bool',
  //   defaultValue: false,
  //   minValue: 0,
  //   maxValue: 1,
  // },
  // [ControlType.STEREO_PAN]: {
  //   name: 'Stereo Pan',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: -1.0,
  //   maxValue: 1.0,
  // },
  // [ControlType.VOICE_COUNT]: {
  //   name: 'Voice Count',
  //   valueType: 'int',
  //   defaultValue: 8,
  //   minValue: 1,
  //   maxValue: 20,
  // },
  [ControlType.ATTACK]: {
    name: 'Attack (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [ControlType.DECAY]: {
    name: 'Decay (sec)',
    valueType: 'float',
    defaultValue: 0.05,
    minValue: 0.0,
    maxValue: 10.0,
  },
  [ControlType.SUSTAIN]: {
    name: 'Sustain',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [ControlType.RELEASE]: {
    name: 'Release (sec)',
    valueType: 'float',
    defaultValue: 0.1,
    minValue: 0.0,
    maxValue: 10.0,
  },
  // [ControlType.OSC_MIX]: {
  //   name: 'Osc Mix',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: 0.0,
  //   maxValue: 1.0,
  // },
  // [ControlType.OSC_MODE]: {
  //   name: 'Osc Mode',
  //   valueType: 'int',
  //   defaultValue: OscMode.MIX,
  //   minValue: 0,
  //   maxValue: OscMode.COUNT - 1,
  // },
  [ControlType.OSC_NOISE_MIX]: {
    name: 'Osc Noise Mix',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  // [ControlType.OSC_PITCH_SHIFT]: {
  //   name: 'Osc Pitch Shift',
  //   valueType: 'float',
  //   defaultValue: 0.0,
  //   minValue: -4.0,
  //   maxValue: 4.0,
  // },
  [ControlType.OSC_SHAPE]: {
    name: 'Osc Shape',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
  [ControlType.OSC_SKEW]: {
    name: 'Osc Skew',
    valueType: 'float',
    defaultValue: 0.0,
    minValue: -0.5,
    maxValue: 0.5,
  },
  // [ControlType.SLICE_MODE]: {
  //   name: 'Slice Mode',
  //   valueType: 'int',
  //   defaultValue: SliceMode.SUSTAIN,
  //   minValue: 0,
  //   maxValue: SliceMode.COUNT - 1,
  // },
  [ControlType.FILTER_TYPE]: {
    name: 'Filter Type',
    valueType: 'int',
    defaultValue: FilterType.NONE,
    minValue: 0,
    maxValue: FilterType.COUNT - 1,
  },
  [ControlType.FILTER_FREQUENCY]: {
    name: 'Filter Frequency',
    valueType: 'float',
    defaultValue: 48000.0,
    minValue: 0.0,
    maxValue: 48000.0,
  },
  [ControlType.FILTER_Q]: {
    name: 'Filter Q',
    valueType: 'float',
    defaultValue: Math.sqrt(0.5),
    minValue: 0.1,
    maxValue: 10,
  },
  [ControlType.BIT_CRUSHER_DEPTH]: {
    name: 'Bitcrusher Depth',
    valueType: 'float',
    defaultValue: 16.0,
    minValue: 1.0,
    maxValue: 16.0,
  },
  [ControlType.BIT_CRUSHER_RATE]: {
    name: 'Bitcrusher Rate',
    valueType: 'float',
    defaultValue: 1.0,
    minValue: 0.0,
    maxValue: 1.0,
  },
};
