name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    name: benchmark on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: benchmark.json
          key: ${{ runner.os }}-benchmark
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        shell: bash
        run: mv benchmark.json benchmark_cached.json
      - name: build
        shell: bash
        run: |
          python build.py --config=release --benchmark \
            --benchmark_out="${{ github.workspace }}/benchmark.json" \
            --benchmark_compare="${{ github.workspace }}/benchmark_cached.json"

  test:
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: python build.py --examples --test --unity

  unity:
    name: unity on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: build
        shell: bash
        run: python build.py --android --unity
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
