name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  examples:
    name: examples on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - name: build
        shell: bash
        run: python build.py --examples
      - uses: actions/upload-artifact@v6
        with:
          name: examples-${{ matrix.os }}
          path: build/**/bin/examples/**/*_demo*

  godot:
    name: godot on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
      - name: build
        shell: bash
        run: python build.py --android --godot
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: actions/upload-artifact@v6
        with:
          name: godot-${{ matrix.os }}
          path: platforms/godot/project/addons/barelymusician/bin

  unity:
    name: unity on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
      - name: build
        shell: bash
        run: python build.py --android --unity
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: actions/upload-artifact@v6
        with:
          name: unity-${{ matrix.os }}
          path: platforms/unity/Assets/BarelyMusician/Plugins

  deploy:
    name: artifacts
    needs: [examples, godot, unity]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          path: temp
      - name: examples
        shell: bash
        run: |
          mkdir -p temp/examples
          for dir in temp/examples-*/; do
            for platform_dir in "${dir}"*/; do
              platform=$(basename "${platform_dir}")
              mkdir -p temp/examples/${platform}
              find "${platform_dir}"* -type f -name '*_demo*' \
                -exec cp {} "temp/examples/${platform}/" \;
            done
          done
          mkdir -p artifacts
          cd temp/examples
          zip -r ${{ github.workspace }}/artifacts/examples.zip *
      - name: godot
        shell: bash
        run: |
          mkdir -p platforms/godot/project/addons/barelymusician/bin
          for dir in temp/godot-*/; do
            cp -rf "${dir}"* platforms/godot/project/addons/barelymusician/bin/
          done
          mkdir -p artifacts
          cd platforms/godot/project
          zip -r ${{ github.workspace }}/artifacts/barelymusiciangodot.zip *
      - name: unity
        shell: bash
        run: |
          for dir in temp/unity-*/; do
            cp -rf "${dir}"* platforms/unity/Assets/BarelyMusician/Plugins/
          done
          mkdir -p artifacts
          cd platforms/unity
          find Assets/ -name \*.meta >> meta
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: ${{ github.workspace }}/artifacts/barelymusician.unitypackage
          include-files: platforms/unity/meta
          project-folder: platforms/unity
          working-folder: ${{ github.workspace }}
      - uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ github.sha }}
          path: artifacts
      - name: draft release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          name: barelymusician ${{ github.ref_name }}
          files: |
            artifacts/barelymusician.unitypackage
            artifacts/barelymusiciangodot.zip
            artifacts/examples.zip
