name: test-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sudo apt-get install -y libasound-dev
        run: sudo apt-get install -y libasound-dev
      - name: bazel test --test_output=errors ...
        run: bazel test --test_output=errors ...

  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel test --test_output=errors ...
        run: bazel test --test_output=errors ...

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel test --test_output=errors ...
        run: bazel test --test_output=errors ...
